- bin/plenv-install
Currently `plenv-install` uses the same directory `$PLENV_ROOT/build` for each build.
This causes errors when we build the same version perl multiple times.
Please look at https://gist.github.com/shoichikaji/2e949a04b44d72379d2f
These are not fatal, but I think `plenv-install` should use different directory for each build.
> use different directory for each build

- lib/Perl/Build.pm
For whatever reason, I have seen the cpan version feed come through without newlines (possibly mobile operator interference), but IMO the 'scraping' code could be more robust to cope with this, and also variations in the HTML
the regex change is tuned to match the tarball
> fix for issue #46 - the cpan version feed can come through without newlines

- t/02_perl_release.t
Because old RC versions were removed.
There is no appropriate RC version like 5.24-RC now if RC versions <= 22 are removed.
This is related to #53.
> Remove RC version

- lib/Perl/Build.pm
It looks like ```plenv install blead``` hasn't been working for a while. This should fix the issue.
> blead.tar.gz is now extracted into perl-blead-(hash), not perl-(hash)

- lib/Perl/Build.pm
Which allows passing stuff to "make install" (such as DESTDIR).
> Support PERL_BUILD_INSTALL_OPTIONS env var.

- bin/plenv-install
Fix #63 
As described in #63, I don't think plenv-install should set `-Dusedevel` by default.
This PR removes `-Dusedevel`.
With this PR, the installation of developer releases will abort.
https://gist.github.com/skaji/bc2a4a5d7116315a7ab174aa63116172
Of course, if you exec plenv-install by `plenv install -Dusedevel 5.27.9`, you can install developer releases.
I also added `-Dversiononly` which installs the perl distribution with a version-specific suffix (eg: `perl5.26.1`, `prove5.26.1`, ...). This used be enabled because `-Dusedevel` implied it.
If you do not want this option anymore, please let me know.
> No -Dusedevel by default

- Build.PL
- META.json
- README.md
- minil.toml
latest Minilla uses Module::Build::Tiny as a default module builder. we need to specify Module::Builder immediately.
> Support latest minilla

- author/fatpack.sh
- cpanfile
- lib/Perl/Build.pm
- t/02_perl_release.t
See https://log.perl.org/2018/05/goodbye-search-dot-cpan-dot-org.html
> use metacpan to find perl releases instead of cpansearch

- lib/Perl/Build.pm
599 is a special internal error code for HTTP::Tiny
Also prune dead whitespace
See https://github.com/tokuhirom/Perl-Build/issues/66
> If error status is 599 also display content

- lib/Perl/Build.pm
`perl_release_by_perl_releases_page` was added in #26. (Many thanks @kazeburo!)
Unfortunately it seems that it is not updated recently.
I think we can rely on MetaCPAN for resolving perl releases URLs, etc.
So this PR removes `perl_release_by_perl_releases_page`.
I will create another PR that adds a MetaCPAN resolver.
> Remove perl_release_by_perl_releases_page

- bin/plenv-install
- script/perl-build
Because we fatpack `lib/**/*.pm` files, we do not need to use lib "lib".
> no need to use lib "lib"

- author/fatpack.pl
- cpanfile
- lib/Perl/Build.pm
- lib/Perl/Build/Built.pm
* Lancaster Consensus says the Perl toolchain will target Perl 5.8.1
* Perl-Build works fine with 5.8.1 without any modification
So I think it is worth to lower perl requirement.
> perl 5.8.2 -> 5.8.1

- lib/Perl/Build.pm
MetaCPAN may return tar.xz perl release URL. So we should take care of it.
P.S.
Should we prefer tar.xz to tar.gz?
> take care of tar.xz

- author/cpanfile.snapshot
- author/fatpack.pl
Fix #82 
On CentOS 6 and 7, `yum install perl` does not install ExtUtils::MakeMaker.
On the other hand, Devel::PatchPerl uses ExtUtils::MakeMaker.
https://github.com/bingos/devel-patchperl/blob/95826fad7e96f573dad727374cfb9f4a8b1017ee/lib/Devel/PatchPerl.pm#L345
This PR adds ExtUtils::MakeMaker in fatpacked script.
> fatpack EUMM for centos

- lib/Perl/Build.pm
before
```
❯ /usr/bin/perl ./perl-build 5.28.0 foo
Fetching 5.28.0 as /var/folders/9j/xylqh05507j22rcpxpfxr2mw0000gn/T/bMT4NlTIgW/perl-5.28.0.tar.gz (https://cpan.metacpan.org/authors/id/X/XS/XSAWYERX/perl-5.28.0.tar.gz)
Cannot get file from https://cpan.metacpan.org/authors/id/X/XS/XSAWYERX/perl-5.28.0.tar.gz: 599 Internal Exception at ./perl-build line 10353.
```
after
```
❯ /usr/bin/perl ./perl-build 5.28.0 foo
Fetching 5.28.0 as /var/folders/9j/xylqh05507j22rcpxpfxr2mw0000gn/T/O3qNLGWP4C/perl-5.28.0.tar.gz (https://cpan.metacpan.org/authors/id/X/XS/XSAWYERX/perl-5.28.0.tar.gz)
Cannot get file from https://cpan.metacpan.org/authors/id/X/XS/XSAWYERX/perl-5.28.0.tar.gz: 599 Internal Exception, Can't verify SSL peers without knowing which Certificate Authorities to trust
This problem can …
```
> dump response body if http status = 599

- script/perl-build
Currently if you pass a path to a .tar.xz file it will fallback to assuming it is a perl version to look up.
> Allow installing from local tar.xz

- script/perl-build
When requesting the URL `http://perl5.git.perl.org/perl.git/snapshot/blead.tar.gz` for blead perl, it is redirected to an `https` URL. This is a problem because HTTP::Tinyish uses the original URL to determine whether it needs to find a user agent with HTTPS support, so it may select one without that support and then fail because of the redirect.
> use https explicitly for installing blead perl

- bin/plenv-install
before
```
❯ perl bin/plenv-install --version
Use of uninitialized value $Perl::Build::VERSION in concatenation (.) or string at bin/plenv-install line 63.
```
after
```
❯ perl bin/plenv-install --version
1.29
```
> fix plenv install --version

- lib/Perl/Build.pm
- script/perl-build
Fixes #94 
perl5.git.perl.org is likely going to be retired soon, so this updates Perl::Build to use github to fetch the blead archive.  The archive from GitHub has a different name for the top level directory, so the code has been refactored to cope with any top level directory.  This removes the need for the blead and cperl special cases.
This can't be merged until Perl/perl5#17199 or something similar is merged into perl core.
> Use github for blead archive

- script/perl-build
before
```
❯ perl -Ilib script/perl-build --version
1.31
```
after
```
❯ perl -Ilib script/perl-build --version
perl-build 1.31 (script/perl-build)
perl 5.032001 (/Users/skaji/env/plenv/versions/5.32.1/bin/perl)
Devel::PatchPerl 2.08
```
> show perl & Devel::PatchPerl versions in perl-build --version

- META.json
- README.md
- lib/Perl/Build.pm
https://github.blog/2021-09-01-improving-git-protocol-security-github/
GitHub disabled `git://` on March 15, 2022.
So let's use https:// instead.
fyi. <https://github.com/tokuhirom/Minilla/pull/315>
> use https for github urls
